### ISSUE TITLE
it always shows wrong client path

### ISSUE THREAD

**Issue by Andy766** [Meviii/LOL-Account-Checker#47]
I'm pretty sure that I have set it up correctly.
![image](https://user-images.githubusercontent.com/58882497/231743293-3bef2f61-e96c-4f65-ae85-ed4a51cd9523.png)

**Comment by Meviii** [comment]
Send a screenshot of your settings.

**Comment by Meviii** [comment]
Regarding the use of a VPN or how many accounts you need to check. The code you linked is 7 years old and makes API calls to the riot server directly for data which is why they want you to use proxies/vpn. My application only makes calls via the LCU (League Client) API which is fairly different so I don't think you would need a VPN (however I cannot guarantee that). I also don't expect anyone to have more than 100+ accounts unless you are using it for illegal purposes which I do not condone.
