### ISSUE TITLE
Riot API Error

### ISSUE THREAD

**Issue by faroldelua** [Meviii/LOL-Account-Checker#49]
![image](https://user-images.githubusercontent.com/109042993/232662221-7fd8f55e-601d-4647-a0e3-9816d7b91bdf.png)

**Comment by Rempacious** [comment]
Same problem

**Comment by Nioxito** [comment]
I think it's a Threads problem, if you try to enter through normal Riot when it tells you to try again in 5 minutes because of an api problem, the riot launcher tells you that it's not possible because it has been tried too many times (basically, it blocks the connection for too many attempts in a short time), maybe if the dev adds the proxy option it will be solved or with NordVPN that automatically rotates the IP every so often (it has worked for me in 2 threads without failure)

**Comment by Meviii** [comment]
> I think it's a Threads problem, if you try to enter through normal Riot when it tells you to try again in 5 minutes because of an api problem, the riot launcher tells you that it's not possible because it has been tried too many times (basically, it blocks the connection for too many attempts in a short time), maybe if the dev adds the proxy option it will be solved or with NordVPN that automatically rotates the IP every so often (it has worked for me in 2 threads without failure)

If that's the case, there is no harm in implementing a proxy option. Ill add with the other changes and release it next week
